version: '3.1'

services:

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - "27017:27017"
    networks:
        testing_net:
            ipv4_address: 172.20.0.3

      
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitMq
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq"
    restart: always
    environment: 
        RABBITMQ_DEFAULT_USER: "rabbitMq"
        RABBITMQ_DEFAULT_PASS: "rabbitMq"
        RABBITMQ_DEFAULT_VHOST: "/"
    networks:
        testing_net:
            ipv4_address: 172.20.0.4
        
  auth:
    image: auth
    hostname: auth
    ports:
        - "8081:80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 172.20.0.5
            
  todo:
    image: todo
    hostname: todo
    ports:
        - "8082:80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 172.20.0.6
            
  gatewayapi:
    image: gatewayapi
    hostname: gatewayapi
    ports:
        - "8080:80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 172.20.0.7
            
  notifications:
    image: notifications
    hostname: notifications
    ports:
        - "8079:80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 172.20.0.8 
            
  ui:
    image: ui
    hostname: ui
    ports:
        - "80:80"
    restart: always
    networks:
        testing_net:
            ipv4_address: 172.20.0.9                          
  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
